# create docker-compose for website folder with golang

version: '3.7'

services:

  website:
    build: ./website
    ports:
      - "8000:8000"
    environment:
      - USERS_API_URL=http://users:4000/api/users/

  users:
    build: ./users
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: logistiktani
    volumes:
      - logistik_tani_db:/var/lib/mysql

volumes:
  logistik_tani_db: