version: '3.8'

services:
  inventory:
    build:
      context: ./inventory
      dockerfile: Dockerfile
    container_name: inventory_service
    ports:
      - "4001:4001"  # Map the host port to the container port
    env_file:
      - ./inventory/.env
    depends_on:
      - db

  sales:
    build:
      context: ./sales
      dockerfile: Dockerfile
    container_name: sales_service
    ports:
      - "4002:4002"
    env_file:
      - ./sales/.env
    depends_on:
      - db

  db:
    image: mysql:latest  
    container_name: database_service
    ports:
      - "3308:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  db_data:
