-- DROP DATABASE IF EXISTS crmtani_user;

CREATE DATABASE IF NOT EXISTS crmtani_inventory;
USE crmtani_inventory;

CREATE TABLE IF NOT EXISTS Inventory (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_user INT NOT NULL,
    nama_produk VARCHAR(100) NOT NULL,
    hpp INT DEFAULT 0,
    harga_jual INT DEFAULT 0,
    kategori VARCHAR(100) NOT NULL,
    jenis VARCHAR(100) NOT NULL,
    stok_aktif INT DEFAULT 0,
    varietas VARCHAR(100) NOT NULL,
    status VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
