CREATE DATABASE IF NOT EXISTS crmtani_user;
USE crmtani_user;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    alamat VARCHAR(255),
    telp VARCHAR(15),
    role VARCHAR(15) NOT NULL,

    saldo BIGINT UNSIGNED DEFAULT 0,
    last_login VARCHAR(100) NULL DEFAULT NULL,
    alamat_kebun VARCHAR(255),
    total_obat BIGINT UNSIGNED DEFAULT 0,
    total_pupuk BIGINT UNSIGNED DEFAULT 0,
    total_bibit BIGINT UNSIGNED DEFAULT 0,
    total_tebu BIGINT UNSIGNED DEFAULT 0,
    luas_lahan BIGINT UNSIGNED DEFAULT 0,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
